### ISSUE TITLE
API Erreur 500

### ISSUE THREAD

**Issue by rtorrente** [jpty/Jeedom-plugin-rteEcowatt#23]
Le plugin semble faire un appel sur l'url suivante : https://digital.iservices.rte-france.com/open_api/tempo_like_supply_contract/v1/tempo_like_calendars?start_date=1970-01-01T01:00:00+01:00&end_date=2023-09-07T00:00:00+02:00&fallback_status=false

Avec start_date=1970-01-01T01:00:00+01:00

Il y a probablement eu un changement sur l'API RTE qui refuse de répondre avec "The API does not provide feedback on such a long period in one call. To retrieve all the data please make it with severals calls to the API."

<img width="1273" alt="image" src="https://github.com/jpty/Jeedom-plugin-rteEcowatt/assets/11695026/ee781be3-305f-4c52-bf51-213d3b2a5359">

**Comment by jpty** [comment]
Merci du retour.
Corrigé dans la branche dev actuelle.
La beta sera diffusée dés que les jours Tempo rouge seront épuisés.
